#!/bin/bash
#                                                                    2020-02-01
#  ERASE ServiceWP files
#
#
pause(){ #  continue or exit
#  echo "----------------------------------------------------------------|"
  read -rsp $'Press any key to continue or ^C to exit ...' -n 1 key
}
#
HOME="/home/yesfi/"
CONFIGDIR=${HOME}"dockrepo/sysdata/servicewp/servicewpconfig/"
SERVICEDIR=${HOME}"dockrepo/sysdata/servicewp/var_www_servicewp"
#
echo
echo
echo "---------------------------------------------------------"
echo "Cancellazione completa dei file di ServiceWP"
echo 
echo "Eseguire SOLO per ripartire completamente da zero"
echo
cd ${SERVICEDIR}
echo "ATTENZIONE !!"
echo "Stiamo per CANCELLARE questo dir:"
pwd
ls -la
echo
pause
echo
echo
sudo rm -rf *
sudo rm -f .htaccess
echo
echo "---------------------------------------------------------"
echo "Nuovo contenuto in:"
pwd
ls -la
echo
echo "Done."
