#!/bin/bash
#                                                                     2021-04-10
#  Generalized 'start app'
#                                                   (in droplet gothings-vo9-db)
#
version="0.01.01"
# include app parameters
source APPNAME
#
echo
echo
echo "---------------------------------------------------------"
echo "Use docker-compose to START the app ${SERVICENAME}"
echo
echo "Starting docker-compose ..."
cd ${WORKDIR}
docker-compose -f "${SERVICENAME}.yml" up -d
echo
echo "Running containers now are:"
~/showdock
echo
echo "Done."